version: '3.9'

services:



  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules 

    command: npm run dev -- --port 3000
    ports:
      - 3000:3000
    stdin_open: true
    tty: true


    